### ISSUE TITLE
The login or Sign up is not working correctly !

### ISSUE THREAD

**Issue by abdimk** [chapaedb/ALX_Portfolio#1]
when the Login or Sign up button is pressed on here https://chapaedb.github.io/ALX_Portfolio/# it does't work its for those reasons

## Reasons Could be
1. You haven't installed php on the server correctly 
2. You haven't configured the php.ini correctly
3. The file hasn't been included in the server folder 

check that !

**Comment by chapaedb** [comment]
Dear Abdisa, thank you for raising the issue, I just deployed the static page here on github that is why is not responding.
I would rather refer you to visit the site I have deployed using Nginx, and ubuntu remote server @ chapaedb.tech
