### ISSUE TITLE
Fix the css code 

### ISSUE THREAD

**Issue by abdimk** [chapaedb/ALX_Portfolio#2]
You need to fix the css code targeting the nav sections 

## our packages 
this need to be aligned correctly 

in the contact section you need to fix the alignment with the h1 tag and add some more css property 
 
follow us part is need to be aligned wit the rest and reduce the size of it 

<strong>NOTE</strong> 
if you need one page designs you can check colorlib

**Comment by chapaedb** [comment]
Well noted!

**Comment by abdimk** [comment]
Nice :)
